### ISSUE TITLE
Gran trabajo!!!

### ISSUE THREAD

**Issue by jevillanueva** [joserra71/psg-example#1]
Muy genial con los retos!! felicidades!!!

- Por si no encuentras los retos de la Sesión 04: https://study.pylapaz.org/content/sesion04/#/60

Sigue adelante! :D

**Comment by joserra71** [comment]
Muchas gracias!

**Comment by jevillanueva** [comment]
Hola nuevamente!
Veo que aun faltan retos del python study group....  
Me gustaria invitarte a que continues 😄 
Aquí encontrarás todas las sesiones y sus retos  https://study.pylapaz.org/
No te desanimes!! estare atento a tus retos, animo!!! 

---
Feedback:
Los retos de las sesiónes 4 y 5 estan super bien, ya me dio curiosidad el juego que propusiste que quisiera verlo desarrollado jeje....
5.5. El notebook me sale invalido que no tiene contenido q se encuentra vacio...

Aun tienes disponibles los retos de las demas sesiones de la 6 hasta la 10
Se que lo harás muy bien tienes madera de un buen dev... y si tienes alguna duda tienes el grupo de whatsapp y tambien este thread
Animo, tienes buen código!!

> El código limpio siempre parece que fue escrito por alguien que se preocupaba. - Michael Feathers

**Comment by joserra71** [comment]
Hola perdon, se me atravesó un problema familiar, voy a retomar los retos y
seguir adelante, si todavía es posible, mil gracias por el apoyo
🙏🙏
